import { Event, User, RSVP, Badge } from "./types";

export const MOCK_USERS: User[] = [
  {
    walletAddress: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
    displayName: "SolanaMaxi.sol",
    avatar: "https://api.dicebear.com/9.x/identicon/svg?seed=7xKXtg2CW87d",
    bio: "Building the future on Solana. Event organizer and community builder.",
    joinedAt: "2024-03-15",
    eventsAttended: ["evt-1", "evt-2", "evt-3"],
    eventsCreated: ["evt-1", "evt-4", "evt-7"],
    reputationScore: 850,
    badges: [
      {
        id: "badge-1",
        name: "Early Adopter",
        description: "One of the first 100 users on Eventerz",
        icon: "Star",
        earnedAt: "2024-03-15",
        tier: "gold",
      },
      {
        id: "badge-2",
        name: "Event Organizer",
        description: "Created 3+ events on Eventerz",
        icon: "Target",
        earnedAt: "2024-04-20",
        tier: "silver",
      },
      {
        id: "badge-3",
        name: "Community Builder",
        description: "Attended 10+ events",
        icon: "Mountain",
        earnedAt: "2024-05-10",
        tier: "bronze",
      },
    ],
  },
  {
    walletAddress: "DRpbCBMxVnDK7maPMoWdfFc3qG7fkGPfRYz5y7j1LqXN",
    displayName: "CryptoAlice",
    avatar: "https://api.dicebear.com/9.x/identicon/svg?seed=DRpbCBMx",
    bio: "Solana developer and hackathon enthusiast.",
    joinedAt: "2024-04-01",
    eventsAttended: ["evt-1", "evt-3", "evt-5"],
    eventsCreated: ["evt-2", "evt-5"],
    reputationScore: 620,
    badges: [
      {
        id: "badge-4",
        name: "Hackathon Hero",
        description: "Attended 3+ hackathons",
        icon: "Laptop",
        earnedAt: "2024-06-15",
        tier: "silver",
      },
    ],
  },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: "evt-1",
    title: "Solana Breakpoint 2026",
    description:
      "The premier annual Solana conference bringing together builders, developers, and community members from around the world. Three days of keynotes, workshops, hackathons, and networking. Learn about the latest innovations in DeFi, NFTs, gaming, and infrastructure on Solana.",
    bannerImage: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&h=600&fit=crop",
    date: "2026-10-15",
    startTime: "09:00",
    endTime: "18:00",
    venue: "Amsterdam RAI Convention Center",
    isOnline: false,
    category: "conferences",
    capacity: 5000,
    rsvpCount: 3847,
    organizer: {
      walletAddress: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
      displayName: "SolanaMaxi.sol",
      avatar: "https://api.dicebear.com/9.x/identicon/svg?seed=7xKXtg2CW87d",
    },
    attendees: [
      "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
      "DRpbCBMxVnDK7maPMoWdfFc3qG7fkGPfRYz5y7j1LqXN",
    ],
    schedule: [
      { time: "09:00", title: "Registration and Welcome Coffee" },
      { time: "10:00", title: "Opening Keynote", speaker: "Anatoly Yakovenko" },
      { time: "11:30", title: "State of Solana DeFi", speaker: "Mert Mumtaz" },
      { time: "13:00", title: "Lunch Break" },
      { time: "14:00", title: "Developer Workshop: Anchor 2.0" },
      { time: "16:00", title: "Community Panel" },
      { time: "17:30", title: "Closing and Networking" },
    ],
    tags: ["solana", "conference", "web3", "defi"],
    createdAt: "2026-06-01",
    isFeatured: true,
  },
  {
    id: "evt-2",
    title: "Grizzlython Hackathon",
    description:
      "A 48-hour online hackathon focused on building innovative dApps on Solana. Categories include DeFi, NFTs, Social, Gaming, and Infrastructure. Over $100K in prizes with mentorship from top Solana projects.",
    bannerImage: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1200&h=600&fit=crop",
    date: "2026-09-20",
    startTime: "10:00",
    endTime: "22:00",
    venue: "Online - Discord",
    isOnline: true,
    category: "hackathons",
    capacity: 2000,
    rsvpCount: 1456,
    organizer: {
      walletAddress: "DRpbCBMxVnDK7maPMoWdfFc3qG7fkGPfRYz5y7j1LqXN",
      displayName: "CryptoAlice",
      avatar: "https://api.dicebear.com/9.x/identicon/svg?seed=DRpbCBMx",
    },
    attendees: ["DRpbCBMxVnDK7maPMoWdfFc3qG7fkGPfRYz5y7j1LqXN"],
    schedule: [
      { time: "10:00", title: "Hackathon Kick-off" },
      { time: "11:00", title: "Sponsor Pitches" },
      { time: "12:00", title: "Hacking Begins" },
      { time: "18:00", title: "Mentor Office Hours" },
    ],
    tags: ["hackathon", "solana", "building", "prizes"],
    createdAt: "2026-06-15",
    isFeatured: true,
  },
  {
    id: "evt-3",
    title: "Solana NYC Meetup #42",
    description:
      "Monthly community meetup for Solana builders in NYC. This month features lightning talks on compressed NFTs, a Blinks deep dive, and open networking. Free pizza and drinks included.",
    bannerImage: "https://images.unsplash.com/photo-1511578314322-379afb476865?w=1200&h=600&fit=crop",
    date: "2026-08-28",
    startTime: "18:30",
    endTime: "21:00",
    venue: "WeWork, 315 W 36th St, New York",
    isOnline: false,
    category: "meetups",
    capacity: 120,
    rsvpCount: 98,
    organizer: {
      walletAddress: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
      displayName: "SolanaMaxi.sol",
      avatar: "https://api.dicebear.com/9.x/identicon/svg?seed=7xKXtg2CW87d",
    },
    attendees: [
      "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
      "DRpbCBMxVnDK7maPMoWdfFc3qG7fkGPfRYz5y7j1LqXN",
    ],
    schedule: [
      { time: "18:30", title: "Doors Open and Networking" },
      { time: "19:00", title: "Lightning Talk: Compressed NFTs", speaker: "Jake" },
      { time: "19:30", title: "Deep Dive: Solana Blinks", speaker: "Maria" },
      { time: "20:00", title: "Open Networking" },
    ],
    tags: ["meetup", "nyc", "community", "networking"],
    createdAt: "2026-07-01",
    isFeatured: false,
  },
  {
    id: "evt-4",
    title: "Jupiter DAO Governance Call",
    description:
      "Monthly DAO governance call for Jupiter community members. Discuss proposals, vote on treasury allocations, and shape the future of the Jupiter ecosystem. All JUP holders welcome.",
    bannerImage: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=1200&h=600&fit=crop",
    date: "2026-09-05",
    startTime: "16:00",
    endTime: "17:30",
    venue: "Online - Google Meet",
    isOnline: true,
    category: "daos",
    capacity: 500,
    rsvpCount: 287,
    organizer: {
      walletAddress: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
      displayName: "SolanaMaxi.sol",
      avatar: "https://api.dicebear.com/9.x/identicon/svg?seed=7xKXtg2CW87d",
    },
    attendees: [],
    schedule: [
      { time: "16:00", title: "Welcome and Agenda" },
      { time: "16:15", title: "Proposal Reviews" },
      { time: "16:45", title: "Community Discussion" },
      { time: "17:15", title: "Voting and Wrap-up" },
    ],
    tags: ["dao", "governance", "jupiter", "voting"],
    createdAt: "2026-07-10",
    isFeatured: false,
  },
  {
    id: "evt-5",
    title: "Solana Gaming Summit",
    description:
      "The ultimate gathering for Solana gaming builders. Explore the latest in on-chain gaming, play-to-earn mechanics, NFT integrations, and game engine tooling. Demo your game to investors and players.",
    bannerImage: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=1200&h=600&fit=crop",
    date: "2026-11-08",
    startTime: "10:00",
    endTime: "20:00",
    venue: "San Francisco Moscone Center",
    isOnline: false,
    category: "gaming",
    capacity: 3000,
    rsvpCount: 2134,
    organizer: {
      walletAddress: "DRpbCBMxVnDK7maPMoWdfFc3qG7fkGPfRYz5y7j1LqXN",
      displayName: "CryptoAlice",
      avatar: "https://api.dicebear.com/9.x/identicon/svg?seed=DRpbCBMx",
    },
    attendees: ["DRpbCBMxVnDK7maPMoWdfFc3qG7fkGPfRYz5y7j1LqXN"],
    schedule: [
      { time: "10:00", title: "Opening Keynote" },
      { time: "11:00", title: "Panel: State of Solana Gaming" },
      { time: "13:00", title: "Lunch and Demo Hall" },
      { time: "14:30", title: "Workshop: Building with Unity + Solana" },
      { time: "16:30", title: "Investor Pitch Session" },
      { time: "18:00", title: "Gaming Tournament" },
    ],
    tags: ["gaming", "p2e", "nft", "solana"],
    createdAt: "2026-07-20",
    isFeatured: true,
  },
  {
    id: "evt-6",
    title: "NFT Creator Workshop",
    description:
      "Learn how to create, mint, and sell NFTs on Solana using Metaplex. From art creation to smart contracts to marketplace listing, this workshop is hands-on for creators of all levels.",
    bannerImage: "https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1200&h=600&fit=crop",
    date: "2026-08-15",
    startTime: "14:00",
    endTime: "17:00",
    venue: "Online - Zoom",
    isOnline: true,
    category: "creator",
    capacity: 200,
    rsvpCount: 156,
    organizer: {
      walletAddress: "DRpbCBMxVnDK7maPMoWdfFc3qG7fkGPfRYz5y7j1LqXN",
      displayName: "CryptoAlice",
      avatar: "https://api.dicebear.com/9.x/identicon/svg?seed=DRpbCBMx",
    },
    attendees: [],
    schedule: [
      { time: "14:00", title: "Introduction to Solana NFTs" },
      { time: "14:45", title: "Hands-on: Creating Your Collection" },
      { time: "15:30", title: "Break" },
      { time: "15:45", title: "Minting and Marketplace Listing" },
      { time: "16:30", title: "Q&A" },
    ],
    tags: ["nft", "creator", "metaplex", "workshop"],
    createdAt: "2026-06-20",
    isFeatured: false,
  },
  {
    id: "evt-7",
    title: "DeFi Deep Dive: Concentrated Liquidity",
    description:
      "A technical workshop exploring concentrated liquidity on Solana DEXs. Learn about CLMM mechanics, LP strategies, and how to build on top of protocols like Orca and Raydium.",
    bannerImage: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1200&h=600&fit=crop",
    date: "2026-09-12",
    startTime: "11:00",
    endTime: "13:00",
    venue: "Online - Twitter Spaces",
    isOnline: true,
    category: "conferences",
    capacity: 1000,
    rsvpCount: 643,
    organizer: {
      walletAddress: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
      displayName: "SolanaMaxi.sol",
      avatar: "https://api.dicebear.com/9.x/identicon/svg?seed=7xKXtg2CW87d",
    },
    attendees: [],
    schedule: [
      { time: "11:00", title: "What is Concentrated Liquidity?" },
      { time: "11:30", title: "CLMM on Solana: Orca and Raydium" },
      { time: "12:00", title: "LP Strategies Workshop" },
      { time: "12:30", title: "Q&A" },
    ],
    tags: ["defi", "clmm", "liquidity", "technical"],
    createdAt: "2026-07-15",
    isFeatured: true,
  },
  {
    id: "evt-8",
    title: "Solana Berlin Meetup",
    description:
      "Connect with Solana builders in Berlin. Lightning talks, live demos, and networking. This month's theme: account compression and ZK proofs.",
    bannerImage: "https://images.unsplash.com/photo-1475721027785-f74eccf877e2?w=1200&h=600&fit=crop",
    date: "2026-10-02",
    startTime: "19:00",
    endTime: "22:00",
    venue: "Factory Berlin, Rheinsberger Str. 76/77",
    isOnline: false,
    category: "meetups",
    capacity: 80,
    rsvpCount: 72,
    organizer: {
      walletAddress: "DRpbCBMxVnDK7maPMoWdfFc3qG7fkGPfRYz5y7j1LqXN",
      displayName: "CryptoAlice",
      avatar: "https://api.dicebear.com/9.x/identicon/svg?seed=DRpbCBMx",
    },
    attendees: [],
    schedule: [
      { time: "19:00", title: "Doors Open" },
      { time: "19:30", title: "Talk: Account Compression", speaker: "Tom" },
      { time: "20:00", title: "Talk: ZK on Solana", speaker: "Lisa" },
      { time: "20:30", title: "Open Networking and Drinks" },
    ],
    tags: ["meetup", "berlin", "zk", "compression"],
    createdAt: "2026-08-10",
    isFeatured: false,
  },
];

export const MOCK_RSVPS: RSVP[] = [
  {
    id: "rsvp-1",
    eventId: "evt-1",
    walletAddress: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
    timestamp: "2024-07-01T10:30:00Z",
    status: "confirmed",
  },
  {
    id: "rsvp-2",
    eventId: "evt-2",
    walletAddress: "DRpbCBMxVnDK7maPMoWdfFc3qG7fkGPfRYz5y7j1LqXN",
    timestamp: "2024-07-15T14:00:00Z",
    status: "confirmed",
  },
  {
    id: "rsvp-3",
    eventId: "evt-3",
    walletAddress: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
    timestamp: "2024-08-05T09:15:00Z",
    status: "confirmed",
  },
];

export const MOCK_BADGES: Badge[] = [
  {
    id: "badge-1",
    name: "Early Adopter",
    description: "One of the first 100 users on Eventerz",
    icon: "Star",
    earnedAt: "2024-03-15",
    tier: "gold",
  },
  {
    id: "badge-2",
    name: "Event Organizer",
    description: "Created 3+ events on Eventerz",
    icon: "Target",
    earnedAt: "2024-04-20",
    tier: "silver",
  },
  {
    id: "badge-3",
    name: "Community Builder",
    description: "Attended 10+ events",
    icon: "Mountain",
    earnedAt: "2024-05-10",
    tier: "bronze",
  },
  {
    id: "badge-4",
    name: "Hackathon Hero",
    description: "Attended 3+ hackathons",
    icon: "Laptop",
    earnedAt: "2024-06-15",
    tier: "silver",
  },
  {
    id: "badge-5",
    name: "Diamond Hands",
    description: "Attended events for 6 consecutive months",
    icon: "Diamond",
    earnedAt: "2024-09-15",
    tier: "diamond",
  },
];
